name: Mostrar informações de commit

on:
  push:
    branches:
      - main  

jobs:
  show-commit-info:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar informações de commit
        run: echo "Commit feito por ${{ github.actor }} em ${{ github.repository }}/${{ github.sha }}"
